---

- name: Install additional packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - libpq-dev
    - libxml2-dev # for lxml
    - libxslt1-dev # for lxml
    - libffi-dev